name: Check for Broken Links on pushed branch

on:
  push:
    branches:
      - test-actions

jobs:
  build_and_check:
    runs-on: ubuntu-latest

    services:
      my_server:
        image: halverneus/static-file-server:v1.7.0
        options: -v ${{ github.workspace }}:/web -p 8000:8080
        env:
          FOLDER: "/web"

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Install dependencies
        run: npm install -g broken-link-checker  # Install the broken-link-checker package globally

      - name: Execute Link Checker and Show Broken Links
        env:
          WEBSITE_URL: "http://my_server:8000"
        run: |
          blc $WEBSITE_URL -ro
