name: Check for Broken Links

on:
  push:
    branches:
      - test-actions

jobs:
  build_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Simple HTTP Server
        run: |
          nohup python -m http.server 8000 &

      - name: Sleep for setup
        run: sleep 10  # Wait for server to setup

      - name: Check if server is up
        run: curl http://localhost:8000

      - name: Install dependencies
        run: npm install -g broken-link-checker  # Install the broken-link-checker package globally

      - name: Execute Link Checker and Show Broken Links
        env:
          WEBSITE_URL: "http://localhost:8000"
        run: |
          blc $WEBSITE_URL -ro
