name: Check for Broken Links

on:
  push:
    branches:
      - test-actions

jobs:
  build_and_check:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - name: Setup Simple HTTP Server
        run: |
          nohup python -m http.server 8000 --bind 127.0.0.1 &  # bind to IPv4 address

      - name: Sleep for setup
        run: sleep 10  # Wait for server to setup

      - name: Check if server is up
        run: curl http://localhost:8000

      - name: Check for broken links with wget
        run: wget --spider -r -nd -nv http://localhost:8000 2>&1 | grep -B 2 'broken link!'
